In [6]:
import numpy as np

## numpy array

In [9]:
benimListem=[20,30,40]

In [11]:
type(benimListem)

list

In [13]:
np.array(benimListem)

array([20, 30, 40])

In [15]:
type(np.array(benimListem))

numpy.ndarray

In [17]:
matrixListesi=[[10,20,30],[20,30,40],[30,40,50]]

In [19]:
type(matrixListesi)

list

In [21]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [24]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [26]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## zeros

In [31]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [37]:
np.zeros((20,20))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [39]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [41]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## linspace

In [46]:
np.linspace(0,20,5)
#3.parametreye göre o mesafede eşit dağıtılmış dizi oluştur

array([ 0.,  5., 10., 15., 20.])

In [51]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## eye

In [49]:
np.eye(3)
#birim matris

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random

In [54]:
np.random.randn(8)

array([ 0.65844094, -0.69972137, -1.53900541,  0.00259795, -0.13768514,
       -0.060693  , -1.1528586 ,  1.87956238])

In [56]:
np.random.randn(4,4)

array([[ 1.40064099,  1.24326944, -1.59276993, -1.64836971],
       [ 1.38280984, -0.75546632,  1.54756775, -0.12377323],
       [ 0.99012046,  0.27932118, -2.0547898 , -0.97426814],
       [-0.2477293 , -1.55201528,  0.32573589,  0.71955115]])

In [58]:
np.random.randint(1,10)
#son yazılan rakamı almaz

9

In [62]:
np.random.randint(1,100,5)

array([51, 11, 17, 56, 89])

In [64]:
benimNumpyDizim=np.arange(30)

In [66]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [72]:
benimRandomDizim=np.random.randint(0,100,30)

In [74]:
benimRandomDizim

array([24, 67, 96, 45, 48,  1, 14, 36, 72, 89, 48, 15, 84,  7, 98,  0, 97,
       46, 94, 52, 74, 45, 56, 47, 47, 56, 35, 56, 17, 33])

## numpy dizi metotları

In [81]:
benimNumpyDizim.reshape(5,6)
#dizi 30 elemanlı olduğu için

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [83]:
benimNumpyDizim.max()

29

In [85]:
benimNumpyDizim.min()

0

In [87]:
benimRandomDizim.max()

98

In [89]:
benimRandomDizim.argmax()

14

In [103]:
reshapedizi=benimNumpyDizim.reshape(6,5)

In [105]:
reshapedizi.shape

(6, 5)

In [107]:
reshapedizi

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])