In [1]:
import numpy as np

In [3]:
benimDizim=np.arange(0,15)

In [5]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
benimDizim[5]

5

In [11]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [13]:
benimDizim[3:8]=-5

In [15]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [17]:
baskaDizi=np.arange(0,24)

In [19]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [35]:
silicingDizi=baskaDizi[4:9]

In [37]:
silicingDizi

array([4, 5, 6, 7, 8])

In [39]:
silicingDizi[:]=700

In [41]:
silicingDizi

array([700, 700, 700, 700, 700])

In [45]:
baskaDizi
#dizinin içinden bir parça alınır o başka bir diziye eşitlenir,
#değişiklikler yapılırsa
#ana dizi de değişiklikleri alır

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [60]:
ornekDizi=np.arange(0,24)

In [62]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [64]:
ornekDiziKopyasi=ornekDizi.copy()

## matrix

In [67]:
benimListem=[[10,20,30],[20,30,40],[40,50,60]]

In [73]:
benimMatrixDizim=np.array(benimListem)

In [77]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [79]:
benimMatrixDizim[0]

array([10, 20, 30])

In [81]:
benimMatrixDizim[1][2]

40

In [83]:
benimMatrixDizim[1,2]

40

In [87]:
benimMatrixDizim[0:,2]

array([30, 40, 60])

In [89]:
yeniListe=[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [91]:
yeniMatrix=np.array(yeniListe)

In [93]:
yeniMatrix[2]

array([10, 11, 12, 13, 14])

In [95]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [97]:
yeniMatrix[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

## operations

In [100]:
yeniBirDizi=np.random.randint(1,100,20)

In [102]:
yeniBirDizi

array([48, 55, 23, 14, 29, 53, 18, 64, 26, 56, 56, 99, 66, 73, 24, 74, 60,
       66, 45, 82])

In [104]:
yeniBirDizi>24

array([ True,  True, False, False,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True])

In [106]:
yeniBirDizi

array([48, 55, 23, 14, 29, 53, 18, 64, 26, 56, 56, 99, 66, 73, 24, 74, 60,
       66, 45, 82])

In [108]:
sonucDizisi=yeniBirDizi>20

In [110]:
sonucDizisi

array([ True,  True,  True, False,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [112]:
yeniBirDizi

array([48, 55, 23, 14, 29, 53, 18, 64, 26, 56, 56, 99, 66, 73, 24, 74, 60,
       66, 45, 82])

In [114]:
yeniBirDizi[sonucDizisi]

array([48, 55, 23, 29, 53, 64, 26, 56, 56, 99, 66, 73, 24, 74, 60, 66, 45,
       82])

In [116]:
yeniBirDizi

array([48, 55, 23, 14, 29, 53, 18, 64, 26, 56, 56, 99, 66, 73, 24, 74, 60,
       66, 45, 82])

In [120]:
yeniBirDizi[yeniBirDizi>25]

array([48, 55, 29, 53, 64, 26, 56, 56, 99, 66, 73, 74, 60, 66, 45, 82])

In [122]:
sonDizi=np.arange(0,24)

In [124]:
sonDizi+sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [126]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [128]:
sonDizi*sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [130]:
sonDizi-sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [132]:
sonDizi/sonDizi

C:\Users\sevva\AppData\Local\Temp\ipykernel_7424\1954055075.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi/sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [134]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [136]:
np.max(sonDizi)

23

In [138]:
np.min(sonDizi)

0